### ISSUE TITLE
'OCP.BRepAlgoAPI.BRepAlgoAPI_Cut' object has no attribute 'SetRunParallel' Error

### ISSUE THREAD

**Issue by jmwright** [CadQuery/OCP#12]
I'm running the latest in the OCP branch of CQ (as of when this is written), and the OCP*.so file downloaded from the release page. Ubuntu 18.04 64-bit. When I try to cut text from a box in the following way, I get the error below. This works in the pre-built release version of CQ-editor.
```python
cq.Workplane("XY").box(10, 10, 0.01).cut(cq.Workplane("XY").workplane(offset=-0.1).text("'Test'", 6, 0.2))

```

```
Font_FontMgr, warning: unable to find font '/usr/share/fonts/truetype/msttcorefonts/Arial.ttf' [regular]; 'Arial' [aspects: regular,bold,italic,bold-italic] [paths: /usr/share/fonts/truetype/msttcorefonts/Arial.ttf;/usr/share/fonts/truetype/msttcorefonts/Arial_Bold.ttf;/usr/share/fonts/truetype/msttcorefonts/ariali.ttf;/usr/share/fonts/truetype/msttcorefonts/arialbi.ttf] is used instead
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jwright/Downloads/repos/cadquery/cadquery/cq.py", line 2780, in cut
    newS = solidRef.cut(*solidToCut)
  File "/home/jwright/Downloads/repos/cadquery/cadquery/occ_impl/shapes.py", line 1999, in cut
    return self._bool_op(self, toCut, cut_op)
  File "/home/jwright/Downloads/repos/cadquery/cadquery/occ_impl/shapes.py", line 598, in _bool_op
    op.SetRunParallel(True)
AttributeError: 'OCP.BRepAlgoAPI.BRepAlgoAPI_Cut' object has no attribute 'SetRunParallel'
```

**Comment by adam-urbanczyk** [comment]
The release is outdated. Latest packages are on our conda channel.
