### ISSUE TITLE
Failed buliding on Fedora

### ISSUE THREAD

**Issue by dov** [CadQuery/OCP#136]
I tried following the instructions in the README.md to compile OCP Fedora 38 but it failed as follows:

```
pywrap -i /usr/include/clang -l /usr/lib64/libclang.so all ocp.toml
  0%|                                                   | 0/314 [00:00<?, ?it/s]joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/clang/cindex.py", line 3832, in register_function
    func = getattr(lib, item[0])
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: /usr/lib64/libclang.so: undefined symbol: clang_CXXMethod_isExplicit

```

pywrap was installed from git with commitid = f3bcde7

ocp was cloned from git and compilation was tried with commit id = 4b98a5dc

**Comment by adam-urbanczyk** [comment]
If you want to just build OCP (i.e. not per se generate it), you can simply use the generated sources https://github.com/CadQuery/OCP/releases/tag/7.7.2.0

IDK what exactly is going wrong, but likely `libclang` has a wrong version, cf https://github.com/CadQuery/OCP/blob/master/environment.devenv.yml
